[Review-Service] 리뷰 조회, 등록, 삭제 구현
personal-preferences/Dong-A-Jul pull request #12
Opened 2024-08-01 11:58 UTC by CJC0512

## #️⃣연관된 이슈
- #3 
- #4 

## 📝작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

- 리뷰 조회, 등록, 삭제 구현 (QueryDSL 및 JPA 활용)
  - 단일 조회(리뷰 ID)
  - 단일 등록
  - ID를 통한 여러 개의 리뷰 조회(회원 ID, 위치 ID)
  - 단일 삭제(리뷰 ID)

- 테스트 코드 작성

### 📷스크린샷 (선택)

## 💬리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

2024-08-01 12:51 UTC, daersh reviewed
리뷰에 대한 등록, 조회, 삭제 로직 확인했습니다.
예외처리, 요청에 대한 validation, mockMvc를 활용한 테스트 방식 참고하겠습니다!

### _**LGTM**_

2024-08-01 12:51 UTC, daersh commented on review_service/src/main/java/org/personal/review_service/controller/ReviewController.java
사용자가 작성한 리뷰가 하나도 없는 경우에도 404 응답이 나오는걸까요?

2024-08-01 12:51 UTC, daersh commented on review_service/src/main/java/org/personal/review_service/repository/ReviewRepository.java
JPAQueryFactory 사용 부분 참고하겠습니다

2024-08-01 12:51 UTC, daersh commented on review_service/src/main/java/org/personal/review_service/service/ReviewServiceImpl.java
builder 중복 부분 통합하면 좋을 것 같습니다

2024-08-01 12:51 UTC, daersh commented on review_service/src/test/java/org/personal/review_service/controller/ReviewControllerTest.java
리뷰 등록, 조회, 삭제에 대한 테스트 확인했습니다
MockMvc 활용부분 참고하여 적용하겠습니다!

2024-08-01 13:04 UTC, CJC0512 commented on review_service/src/main/java/org/personal/review_service/controller/ReviewController.java
헉.. 404가 반환되도록 작성했네요. 
204가 적절해보이니 수정하도록 하겠습니다!

2024-08-02 00:50 UTC, orlzlL approved these changes

2024-08-02 00:50 UTC, orlzlL commented on review_service/src/main/java/org/personal/review_service/service/ReviewServiceImpl.java
엔티티 DTO 간 중복 부분을 메소드로 추출하여 관리하거나 아예 Mapper 클래스로 분리하여 엔티티<->DTO변환 책임을 분리하는 것도 좋을 것 같아요 !

2024-08-02 00:52 UTC, DYShin1 requested changes
수고하셨습니다 👍

2024-08-02 00:52 UTC, DYShin1 commented on review_service/src/main/java/org/personal/review_service/domain/Review.java
혹시 저희 Integer 말고 Long 쓰는건가요???

2024-08-02 00:52 UTC, DYShin1 commented on review_service/src/main/java/org/personal/review_service/repository/ReviewRepository.java
혹시 repository를 여러번 상속하신 이유가 있으신가요?!?!

2024-08-02 01:27 UTC, ms1011 approved these changes
API url 부분하고 댓글 확인부탁드려요
코드 구현하느라 고생하셨어요~

2024-08-02 01:27 UTC, ms1011 commented on review_service/build.gradle
> +	// QueryDSL
이 부분 참고해서 의존성 추가하였습니다 굳굳

2024-08-02 01:27 UTC, ms1011 commented on review_service/src/main/java/org/personal/review_service/controller/ReviewController.java
>  @RequestMapping("/review")
Restful API에서는 복수형을 기본으로 하고 있어요 `/reviews`가 좋을 것 같습니다

2024-08-02 01:27 UTC, ms1011 commented on review_service/src/main/java/org/personal/review_service/domain/Review.java
네 Long으로 어제 합의했습니다

2024-08-02 01:27 UTC, ms1011 commented on review_service/src/main/java/org/personal/review_service/request/ReviewCreate.java
> +        @NotNull(message = "Review content cannot be null")
오류 메시지는 한국어로 하는건 어떠세요?ㅋㅋㅋㅋ

2024-08-02 01:27 UTC, ms1011 commented on review_service/src/test/java/org/personal/review_service/controller/ReviewControllerTest.java
given, when, then 부분을 나눠서 작성하면 좋을 것 같습니다

2024-08-02 01:27 UTC, ms1011 commented on review_service/src/test/java/org/personal/review_service/controller/ReviewControllerTest.java
`ReviewNotFound` 예외 작동 잘 되는 지에 대한 테스트 코드 추가해야할 것 같습니다

2024-08-02 01:30 UTC, DYShin1 approved these changes

2024-08-02 02:21 UTC, Sosohy approved these changes
다들 리뷰를 이미 잘 남겨주셔서 제가 별로 할 말이 없네요ㅎㅎ 
종찬님 코드 참고해서 저도 필요한 부분 보완해보도록 하겠습니다!

2024-08-02 02:21 UTC, Sosohy commented on review_service/src/main/java/org/personal/review_service/repository/ReviewJpaRepository.java
저 어제 이 부분 코드 작성했었는데 밑에 처럼 하나 더 만들어서 할 필요없이 extends JpaRepository<Review, Long>, CustomRepository 이렇게 해도 동작했던 것 같아요!! 참고하시라고 말해봅니다!

2024-08-02 02:43 UTC, CJC0512 commented
리뷰에 따라 수정사항 반영했습니다!

2024-08-02 02:48 UTC, daersh reviewed
변경사항 확인했습니다~!

2024-08-02 04:02 UTC, ms1011 commented
> 리뷰에 따라 수정사항 반영했습니다!

확인했습니다 굳굳

2024-08-02 04:02 UTC, merged