[Registration-Service] 화장실 등록 신청 조회, 정렬
personal-preferences/Dong-A-Jul pull request #39
Opened 2024-08-13 15:11 UTC by DYShin1

## #️⃣연관된 이슈
- #38 

## 📝작업 내용
- 특정 화장실 등록 정보 조회 기능 구현
- 전체 화장실 등록 정보 조회 기능 구현
- 10개씩 Paging 처리
- toiletRegistConfirmedDate null일때 가장 먼저 조회 구현

### 📷스크린샷 (선택)

## 💬리뷰 요구사항(선택)
<img width="799" alt="image" src="https://github.com/user-attachments/assets/ed01aa4b-bfd6-4698-b8f5-6afbe0075d3f">

- OrderBy 추가 하였지만 ToiletRegistApproveServiceImplTests.java 쪽 정렬 테스트가 통과가 안됩니다. 확인 한번만 부탁드리겠습니다!

2024-08-14 02:34 UTC, ms1011 approved these changes
관리자용 기능까지 만드셨네요
고생하셨어요~😀😀

2024-08-14 04:26 UTC, Sosohy approved these changes
조회까지 구현하느라고 수고하셨습니다!! 정렬 부분은 찾아보니까 저렇게 써도 되는 것 같은데 이유가 뭔지,,좀 더 고민해보겠습니다🤯

2024-08-14 05:41 UTC, CJC0512 requested changes

2024-08-14 05:41 UTC, CJC0512 commented on toilet_registration_service/src/test/java/org/personal/registration_service/service/impl/ToiletRegistApproveServiceImplTests.java
> +		doReturn(page).when(toiletRegistRepository).findAllByPageable(pageable);
doReturn으로 강제로 
`Page<ToiletRegist> page = new PageImpl<>(toiletRegistList, pageable, toiletRegistList.size());` 를 반환해주고 있기 때문에 순서상 toiletRegist1이 먼저 들어와 오류를 발생시키는 것 같아요. 

하지만 이건 실제 작동 코드로 인한 오류가 아닌 테스트 코드에서 발생되는 오류이니 실제로는 잘 작동될 것 같습니다.

테스트 코드를 수정한다면 page에서 사용하는 toiletRegistList의 순서만 바꾸면 될 것 같아요.
`    List<ToiletRegist> toiletRegistList = Arrays.asList(toiletRegist2, toiletRegist1); `

2024-08-14 06:22 UTC, DYShin1 commented on toilet_registration_service/src/test/java/org/personal/registration_service/service/impl/ToiletRegistApproveServiceImplTests.java
> +		doReturn(page).when(toiletRegistRepository).findAllByPageable(pageable);
오! 맞네요. 테스트 코드서 비교하려면 순서를 바꿔야하네요. 수정 완료했습니다. 의견 감사합니다!

2024-08-15 06:54 UTC, CJC0512 approved these changes

2024-08-15 09:19 UTC, orlzlL approved these changes
조회 기능 확인했습니다 ~! 구현 고생하셨습니다 😃

2024-08-16 06:31 UTC, daersh commented
화장실 페이지 적용 확인했습니다!
고생하셨습니다!
### _**LGTM**_

2024-08-17 05:21 UTC, merged